version: "{build}"

shallow_clone: true

init:
  - git config --global core.autocrlf false

build: off

environment:
  matrix:
    # node.js
    - nodejs_version: 10.5

install:
  - ps: Install-Product node $env:nodejs_version
  - npm ci

test_script:
  - node --version && npm --version
  - npm test